services:
  java_app:
    container_name: java_app
    build: .
    image: examen-app-productos
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:postgresql://java_db:5432/productos_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:15
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productos_db
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: